project:
  name: "arequipa"
  description: ""
  author: ""
model:
  name: ""
  num_classes: 10

training:
  batch_size: 32
  num_epochs: 25
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "step_lr"
  step_size: 7
  gamma: 0.1

data:
  train_data_path: "/path/to/train/data"
  val_data_path: "/path/to/val/data"
  test_data_path: "/path/to/test/data"
  input_size: 224
  num_workers: 4
  shuffle: True

logging:
  log_dir: "/path/to/logs"
  log_interval: 10

checkpoint:
  save_dir: "/path/to/checkpoints"
  save_interval: 5
  resume_from: "/path/to/checkpoints/latest.pth"

device:
  gpu: true
  gpu_id: 0