project:
  name: "arequipa"
  description: ""
  author: ""

model:
  name: ""
  num_classes: 1 # binary classification

training:
  batch_size: 32
  num_epochs: 25
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "step_lr"
  step_size: 7
  input_dim: 768
  hidden_dim: 128
  dropout_prob: 0.5
  num_layers: 13 # Number of layers in the transformer model

data:
  train_data_path: "/home/aleph/embeddings_classifier/data/arequipa/db.csv"
  val_data_path: "/home/aleph/embeddings_classifier/data/arequipa/db.csv"
  test_data_path: "/home/aleph/embeddings_classifier/data/arequipa/db.csv"
  num_workers: 2
  shuffle: True
  audio_path: "/home/aleph/embeddings_classifier/data/arequipa/audio/"
  audio_embeddings_path: "/home/aleph/embeddings_classifier/data/arequipa/audio_embeddings/"
  text_embeddings_path: "/path/to/text_embeddings"

logging:
  log_dir: "/path/to/logs"
  log_interval: 10

checkpoint:
  save_dir: "models/checkpoints"
  save_interval: 5
  resume_from: "models/checkpoints/latest.pth"

device:
  gpu: true
  gpu_id: 0